### ISSUE TITLE
[CODE][SEGFAULT] bottom knight checkMateToThisTeam()

### ISSUE THREAD

**Issue by haibuinam** [chrisdcao/4P_Network_Chess_Unreal_Engine#10]
Behavior: Lag after click the 2nd click
functions called: CheckMateToThisTeam() -> MovableHashKeys
Re-create: move bottom knight eat right pawn

**Comment by haibuinam** [comment]
[CODE][SEGFAULT] Team Left checkMateToThisTeam()
Behavior:  SEGFAULT whenever playerTurn == - 2 || playerTurn == - 4
functions called: CheckMateToThisTeam() 
Re-create: after move bottom queen to checkmate  right king, Team Left 's turn is error. While Right king is still many turns

![bottom queen checkmate right king](https://user-images.githubusercontent.com/81558779/130418418-bed62a28-501f-4a0d-9bd0-537fd30507cb.JPG)

**Comment by haibuinam** [comment]
[CODE][SEGFAULT] Team Left checkMateToThisTeam()
Behavior: SEGFAULT whenever playerTurn == - 2 || playerTurn == - 4
functions called: OnLeftMouseClick->checkMateToThisTeam-> GetMovableIndicesPawn-> IndexInPieceVectorFromBoardIndex
Re-create:  after move bottom knight eat right pawn -> when next playerTurn move left pawn error
![image](https://user-images.githubusercontent.com/81558779/130430039-cb37810d-8f5f-4cf6-ba56-bc6d9269bd6b.png)

**Comment by chrisdcao** [comment]
thank you for reporting, I will move each into separate bugs and marked as resolved over there as things go!

**Comment by chrisdcao** [comment]
all three bugs are resolved in the latest fix! Thanks for contributing to the project!
