### ISSUE TITLE
[CODE][LOGIC_ERROR] Wrong checkmate status

### ISSUE THREAD

**Issue by chrisdcao** [chrisdcao/4P_Network_Chess_Unreal_Engine#24]
Behavior: When queen Left move to position to checkmate Team Bottom, it's announced that team 2 lose (while it's not)
Suspect: checkMate to this team of team 2
Re-create: as image
![Screenshot_36](https://user-images.githubusercontent.com/68319923/130518896-935a1d91-b002-449b-8f7e-f185990f0c07.png)

**Comment by haibuinam** [comment]
Behavior: When queen bottom move to position to checkmate right king , it doesn't message that team has lose (while the right king has no turn)
Suspect: checkMateToEnemyTeam-> EatableHashKeys
Re-create: as image
![wwrong checkmate](https://user-images.githubusercontent.com/81558779/130550765-04cd080e-8c5e-40a4-8126-7030a2dba7a4.JPG)

**Comment by haibuinam** [comment]
Behavior: When queen left move to position to checkmate bottom king , it doesn't message that "Player1 is currently being checkedMate! " (just it messages  until it is bottom team to turn)
Re-create: as image
![qqqqq](https://user-images.githubusercontent.com/81558779/130554317-f2502c65-e6c1-4c37-b10d-436541843391.JPG)

**Comment by chrisdcao** [comment]
thank you for reporting! these issues are all addressed in the latest update and thus will be closed now
