### ISSUE TITLE
[CODE][LOGIC_ERROR] left queen move to invalid position

### ISSUE THREAD

**Issue by haibuinam** [chrisdcao/4P_Network_Chess_Unreal_Engine#34]
Behavior: left queen move to disallowance position
Suspect functions: GetMovableIndicesQueen, makeMove
Re-create: as image
![hậu đi sai](https://user-images.githubusercontent.com/81558779/130939139-683e851d-bc48-4734-b086-c241f223ed02.JPG)

**Comment by chrisdcao** [comment]
thank you for reporting! after inspection it's found that the bishop moving threshold (in this case DownLeft) is not set tight enough, leading to tile-overflow despite of value (continous calculation leading to value of misplaced tile)

**Comment by chrisdcao** [comment]
fixed in the latest update!
