### ISSUE TITLE
[CODE][SEGFAULT] left Bishop checkMateToThisTeam Player 2

### ISSUE THREAD

**Issue by haibuinam** [chrisdcao/4P_Network_Chess_Unreal_Engine#9]
Behavior: Lag after click the 2nd click
functions called: CheckMateToThisTeam() -> GetMovableIndicesBishop
Re-create: move left bishop eat bottom Bishop

**Comment by chrisdcao** [comment]
this bug is also fixed in the latest update! thanks for reporting
